/*
 * Project          : BmpToOledData
 * File             : Program.cs
 * Version          : 1.0
 * Author           : Alexander Glushanenko
 * Date             : 30.11.2025
 * Description      : The program converts a BMP file into a byte array, ready for transfer as data to an SSD1306-based display.
 *                    The byte array can be saved as a C-file or in raw form as a BIN-file.
 */

using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;

namespace BmpToOledBuf
{
    class Program
    {
        static void Main()
        {
            Console.WriteLine("BmpToOledData v1.0\n");
            Console.Write("Enter BMP file name:");
            string filename = Console.ReadLine();

            if (File.Exists(filename))
            {
                Bitmap bitmap = new Bitmap(filename);
                if(bitmap.PixelFormat == PixelFormat.Format1bppIndexed)
                {
                    if(bitmap.Width > 0)
                    {
                        if (bitmap.Height >= 8)
                        {
                            if (bitmap.Height % 8 == 0)
                            {
                                int pages = bitmap.Height / 8;
                                int columns = bitmap.Width;
                                int bufsize = pages * columns;
                                byte[] buf = new byte[bufsize];
                                int bufcnt = 0;

                                Console.WriteLine("BMP file info:");
                                Console.WriteLine($"  Width: {bitmap.Width} px");
                                Console.WriteLine($"  Height: {bitmap.Height} px");
                                Console.WriteLine("Out buffer info:");
                                Console.WriteLine($"  Columns: {columns}");
                                Console.WriteLine($"  Pages: {pages}");
                                Console.Write($"  Size: {bufsize} bytes\nConverting... ");

                                for (int page = 0; page < pages; page++)
                                {
                                    for (int pixel_x = 0; pixel_x < columns; pixel_x++)
                                    {
                                        int pixel_y = page*8;

                                        byte curbyte = 0;
                                        byte curbit = 0;
                                        for (int i = 0; i < 8; i++)
                                        {
                                            curbit = (bitmap.GetPixel(pixel_x, pixel_y + i).ToArgb() & 0xFFFFFF) == 0 ? (byte)0x01 : (byte)0x00;
                                            curbyte |= (byte)(curbit << i);
                                        }

                                        buf[bufcnt] = curbyte;
                                        bufcnt++;
                                    }
                                }
                                Console.WriteLine("complete.");
                                Console.Write("Output file name:");
                                String outfilename = Console.ReadLine();
                                Console.Write("Select save format (1 - raw binary array; 2 - C-style array): ");
                                String outformat = Console.ReadLine();

                                if (outformat == "1") // raw binary array
                                {

                                    FileStream outfile = File.OpenWrite(outfilename);
                                    outfile.Write(buf, 0, bufsize);
                                    outfile.Close();
                                }
                                else if (outformat == "2") // C-style array
                                {
                                    bool ex = false;
                                    StreamWriter streamWriter = null;
                                    try { streamWriter = new StreamWriter(outfilename, true, System.Text.Encoding.UTF8); }
                                    catch (Exception) { ex = true; }

                                    if(!ex)
                                    {
                                        string comment =
                                            "/* This array is generated by BmpToOledBuf converter.\n"
                                            + "*\n"
                                            + "* Input BMP file info:\n"
                                            + $"*   Width: {bitmap.Width} px\n"
                                            + $"*   Height: {bitmap.Height} px\n"
                                            + "* Out buffer info:\n"
                                            + $"*   Columns: {columns}\n"
                                            + $"*   Pages: {pages}\n"
                                            + $"*   Size: {bufsize} bytes */";

                                        try { streamWriter.Write($"\n#include <stdint.h>\n\n{comment}\n\nconst uint8_t buf[{bufsize}] = {'{'}\n"); }
                                        catch (Exception) { ex = true; };

                                        bufcnt = 0;
                                        for (int page = 0; page < pages && !ex; page++)
                                        {
                                            for (int column = 0; column < columns && !ex; column++)
                                            {
                                                try { streamWriter.Write((column > 0 ? ", " : "    ") + string.Format("0x{0:X2}", buf[bufcnt])); }
                                                catch (Exception) { ex = true; };
                                                bufcnt++;
                                            }
                                            try { streamWriter.Write(page < pages - 1 ? ",\n" : "\n};\n"); }
                                            catch (Exception) { ex = true; };
                                        }
                                    }
                                    if (streamWriter != null) streamWriter.Close();

                                    if(!ex) Console.WriteLine("File saved");
                                    else Console.WriteLine("StreamWriter exception");
                                }
                                else Console.WriteLine("Incorrect input");
                            }
                            else Console.WriteLine("The height of the BMP must be a multiple of 8");
                        }
                        else Console.WriteLine("The height of the BMP should not be less than 8");
                    }
                    else Console.WriteLine("The width of the BMP must be greater than 0");
                }
                else Console.WriteLine("The BMP image must be monochrome (1 bit / pixel)");
            }
            else Console.WriteLine("BMP not found");

            Console.Write("Press any key to exit...");
            Console.ReadKey();
            return;
        }
    }
}
